#!/bin/sh

bspc config border_width        5
bspc config window_gap          10

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{main,gui,code,media}
    let i++
done
NMON=$i
unset i

bspc config top_padding 35
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#4c626d"
bspc config active_border_color "#8c4c4c"
bspc config focused_border_color "#8c4c4c"
bspc config presel_border_color "#907245"
bspc config urgent_border_color "#ae5d5d"
bspc config focused_locked_border_color "#484542"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.0

~/.config/bspwm/panel.sh &
